name: wossvc_hiv
channels:
  - bioconda
  - conda-forge
  - etetoolkit
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - biopython=1.78
  - ete3=3.1.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pip=20.3.3
  - python-docx=0.8.10
  - scipy=1.5.2
  - tn93=1.0.6
  - pip:
    - hivtrace==0.6.2
