name: wossvc_hiv
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.12
  - biopython=1.78
  - python-docx=0.8.10
  - cython=0.29.21
  - pip=20.2.4
  - tn93=1.0.6
  - pyqt=5.9.2
  - ete3=3.1.2
  - pip:
    - hivtrace==0.6.2
    - sierrapy==0.3.0
 